# src/AppBundle/Resources/config/doctrine/Post.orm.yml
AppBundle\Entity\Post:
  type: entity
  #repositoryClass: AppBundle\Repository\PostRepository
  table: post
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
    slug:
      type: string
      length: 255
    summary:
      type: string
      length: 255
    content:
      type: text
    author_email:
      type: string
      length: 255
    published_at:
      type: datetime
  oneToMany:
    comments:
      targetEntity: Comment
      mappedBy: post
      cascade: [ remove ]